package lexer

var ios []Rule = []Rule{
	{
		Description: "WebView Load Request",
		IsAndMatch:  true,
		AndExpressions: []string{
			"loadRequest",
			"webView",
		},
	},
	{
		Description:      "O aplicativo permite certificados SSL autoassinados ou inválidos. O aplicativo é vulnerável a ataques de MITM (Man-In-The-Middle).",
		Recomendation:    "Os certificados devem ser cuidadosamente gerenciados e verificados para garantir que os dados sejam criptografados com a chave pública do proprietário pretendido.",
		ExactMatch:       "canAuthenticateAgainstProtectionSpace|continueWithoutCredentialForAuthenticationChallenge|kCFStreamSSLAllowsExpiredCertificates|kCFStreamSSLAllowsAnyRoot|kCFStreamSSLAllowsExpiredRoots|validatesSecureCertificate\\s*=\\s*(no|NO)|allowInvalidCertificates\\s*=\\s*(YES|yes)",
		Severity:         "high",
		CWE:              "CWE-295",
		OWASPReferenceID: "M3",
	},
	{
		Description:   "O UIWebView no aplicativo ignora erros de SSL e aceita qualquer certificado SSL. O aplicativo é vulnerável a ataques do MITM (Man-In-The-Middle).",
		Recomendation: "Os certificados devem ser cuidadosamente gerenciados e verificados para garantir que os dados sejam criptografados com a chave pública do proprietário pretendido.",
		ExactMatch:    "setAllowsAnyHTTPSCertificate:\\s*YES|allowsAnyHTTPSCertificateForHost|loadingUnvalidatedHTTPSPage\\s*=\\s*(YES|yes)",
		Severity:      "high",
		CWE:           "CWE-295",
	},
	{
		Description:   "O binário pode usar a função NSLog para registro em log. As informações confidenciais nunca devem ser registradas.",
		Recomendation: "Evitar que dados sensíveis sejam logados em produção.",
		ExactMatch:    "NSLog|NSAssert|fprintf|fprintf|Logging",
		Severity:      "info",
		CWE:           "CWE-532",
	},
	{
		Description: "O aplicativo permite listar as alterações no Clipboard. Alguns malwares também listam alterações no Clipboard.",
		ExactMatch:  "UIPasteboardChangedNotification|generalPasteboard\\]\\.string",
		Severity:    "info",
	},
	{
		Description: "A entrada do usuário não sanitizada em 'loadHTMLString' pode resultar em uma injeção de JavaScript no contexto do seu aplicativo, permitindo acesso a dados privados.",
		IsAndMatch:  true,
		AndExpressions: []string{
			"loadHTMLString",
			"webView",
		},
		Severity: "info",
		CWE:      "CWE-95",
	},
	{
		Description:   "MD5 é um hash fraco, podendo gerar hashs repitidos.",
		Recomendation: "Quando for necessário armazenar ou transmitir dados sensíveis, dê preferência a algoritmos de criptografia modernos e verifique com frequência se o algoritmo utilizado não se tornou obsoleto.",
		IsAndMatch:    true,
		AndExpressions: []string{
			"CommonDigest.h",
			"CC_MD5",
		},
		Severity:         "high",
		CWE:              "CWE-327",
		OWASPReferenceID: "M5",
	},
	{
		Description:   "SHA1 é um hash fraco, podendo gerar hashs repitidos.",
		Recomendation: "Quando for necessário armazenar ou transmitir dados sensíveis, dê preferência a algoritmos de criptografia modernos e verifique com frequência se o algoritmo utilizado não se tornou obsoleto.",
		IsAndMatch:    true,
		AndExpressions: []string{
			"CommonDigest.h",
			"CC_SHA1",
		},
		Severity:         "high",
		CWE:              "CWE-327",
		OWASPReferenceID: "M5",
	},
	{
		Description:   "O aplicativo usa o modo ECB no algoritmo de criptografia. Sabe-se que o modo ECB é fraco, pois resulta no mesmo texto cifrado para blocos idênticos de texto sem formatação.",
		Recomendation: "Quando for necessário armazenar ou transmitir dados sensíveis, dê preferência a algoritmos de criptografia modernos e verifique com frequência se o algoritmo utilizado não se tornou obsoleto.",
		IsAndMatch:    true,
		AndExpressions: []string{
			"kCCOptionECBMode",
			"kCCAlgorithmAES",
		},
		Severity: "high",
		CWE:      "CWE-327",
	},
	{
		Description: "O aplicativo pode conter mecanismos de detecção de Jailbreak.",
		IsOrMatch:   true,
		OrExpressions: []string{
			"/Applications/Cydia.app",
			"/Library/MobileSubstrate/MobileSubstrate.dylib",
			"/usr/sbin/sshd",
			"/etc/apt",
			"cydia://",
			"/var/lib/cydia",
			"/Applications/FakeCarrier.app",
			"/Applications/Icy.app",
			"/Applications/IntelliScreen.app",
			"/Applications/SBSettings.app",
			"/Library/MobileSubstrate/DynamicLibraries/LiveClock.plist",
			"/System/Library/LaunchDaemons/com.ikey.bbot.plist",
			"/System/Library/LaunchDaemons/com.saurik.Cydia.Startup.plist",
			"/etc/ssh/sshd_config",
			"/private/var/tmp/cydia.log",
			"/usr/libexec/ssh-keysign",
			"/Applications/MxTube.app",
			"/Applications/RockApp.app",
			"/Applications/WinterBoard.app",
			"/Applications/blackra1n.app",
			"/Library/MobileSubstrate/DynamicLibraries/Veency.plist",
			"/private/var/lib/apt",
			"/private/var/lib/cydia",
			"/private/var/mobile/Library/SBSettings/Themes",
			"/private/var/stash",
			"/usr/bin/sshd",
			"/usr/libexec/sftp-server",
			"/var/cache/apt",
			"/var/lib/apt",
			"/usr/sbin/frida-server",
			"/usr/bin/cycript",
			"/usr/local/bin/cycript",
			"/usr/lib/libcycript.dylib",
			"frida-server",
		},
		Severity: "info",
	},
}
