package analyzers

import "github.com/insidersec/insider/models"

func loadManifestData() []models.ManifestPermission {
	return []models.ManifestPermission{
		{
			Title:       "android.permission.SEND_SMS",
			Status:      "perigoso",
			Description: "Enviar Mensagens SMS",
			Info:        "Permite a aplicação enviar Mensagens SMS. Aplicações maliciosas podem gastar dinheiro enviando mensagens sem sua confirmação.",
		},
		{
			Title:       "android.permission.SEND_SMS_NO_CONFIRMATION",
			Status:      "perigoso",
			Description: "Enviar Mensagens SMS",
			Info:        "Permite o envio de mensagens SMS via aplicativo de mensagens sem entrada ou confirmação do usuário.",
		},
		{
			Title:       "android.permission.CALL_PHONE",
			Status:      "perigoso",
			Description: "Ligar diretamente para números de telefone",
			Info:        "Permite que o aplicativo seja ativado sem a sua intervenção. Os aplicativos maliciosos podem gerar custos inesperados na sua conta telefônica. Observe que isso não permite que o aplicativo ligue para números de emergência.",
		},
		{
			Title:       "android.permission.RECEIVE_SMS",
			Status:      "perigoso",
			Description: "Receber SMS",
			Info:        "Permite que o aplicativo receba e processe mensagens SMS. Os aplicativos maliciosos podem monitorar ou excluir suas mensagens sem você saber.",
		},
		{
			Title:       "android.permission.RECEIVE_MMS",
			Status:      "perigoso",
			Description: "Receber MMS",
			Info:        "Permite que o aplicativo receba e processe mensagens MMS. Os aplicativos maliciosos podem monitorar ou excluir suas mensagens sem você saber.",
		},
		{
			Title:       "android.permission.READ_SMS",
			Status:      "perigoso",
			Description: "Ler SMS ou MMS",
			Info:        "Permite que o aplicativo leia mensagens SMS guardadas no seu telefone ou cartão SIM. Os aplicativos maliciosos podem ler como suas mensagens confidenciais.",
		},
		{
			Title:       "android.permission.WRITE_SMS",
			Status:      "perigoso",
			Description: "Editar SMS ou MMS",
			Info:        "Permite que o aplicativo escreva mensagens SMS guardadas no seu telefone ou cartão SIM. Os aplicativos maliciosos podem excluir suas mensagens.",
		},
		{
			Title:       "android.permission.RECEIVE_WAP_PUSH",
			Status:      "perigoso",
			Description: "Receber WAP",
			Info:        "Permite que o aplicativo receba e processe mensagens WAP. Os aplicativos maliciosos podem monitorar suas mensagens ou excluir-você sem saber.",
		},
		{
			Title:       "android.permission.READ_CONTACTS",
			Status:      "perigoso",
			Description: "ler informações de contato",
			Info:        "Permite a aplicação ler todos os dados de contato (endereço) capturados no seu telefone. Aplicativos maliciosos podem usar isso para enviar seus dados para outras pessoas.",
		},
		{
			Title:       "android.permission.WRITE_CONTACTS",
			Status:      "perigoso",
			Description: "escrever informações de contato",
			Info:        "Permite que o aplicativo modifique os dados de contato (endereço) capturados no seu telefone. Os aplicativos maliciosos podem usar isso para excluir ou modificar os dados de contato.",
		},
		{
			Title:       "android.permission.READ_PROFILE",
			Status:      "perigoso",
			Description: "ler os dados do perfil pessoal do usuário",
			Info:        "Permite que a Aplicação leia os dados pessoais do usuário.",
		},
		{
			Title:       "android.permission.WRITE_PROFILE",
			Status:      "perigoso",
			Description: "escrever os dados do perfil pessoal do usuário",
			Info:        "Permite que oa aplicação escrita (mas não leia) leia os dados pessoais do usuário.",
		},
		{
			Title:       "android.permission.READ_SOCIAL_STREAM",
			Status:      "perigoso",
			Description: "ler a partir do fluxo social do usuário",
			Info:        "Permite que o aplicativo leia a partir do fluxo social do usuário.",
		},
		{
			Title:       "android.permission.WRITE_SOCIAL_STREAM",
			Status:      "perigoso",
			Description: "escrever a partir do fluxo social do usuário",
			Info:        "Permite que o aplicativo escreva a partir do fluxo social do usuário.",
		},
		{
			Title:       "android.permission.READ_CALENDAR",
			Status:      "perigoso",
			Description: "ler eventos da agenda",
			Info:        "Permite a aplicação ler todos os eventos da agenda armazenados no seu telefone. Aplicativos maliciosos podem usar isso para enviar seus eventos da agenda para outras pessoas.",
		},
		{
			Title:       "android.permission.WRITE_CALENDAR",
			Status:      "perigoso",
			Description: "adicionar ou modificar eventos da agenda e enviar e-mails aos convidados",
			Info:        "Permite a aplicação adicionar ou alterar os eventos do seu calendário, o que pode enviar e-mails para convidados. Aplicativos maliciosos podem usar isso para excluir ou modificar os eventos da sua agenda ou enviar e-mails para os convidados. ",
		},
		{
			Title:       "android.permission.READ_USER_DICTIONARY",
			Status:      "perigoso",
			Description: "ler dicionário definido pelo usuário",
			Info:        "Permite a aplicação palavras-chave exclusivas, nomes e frases particulares que o usuário possa ter armazenado no dicionário do usuário.",
		},
		{
			Title:       "android.permission.WRITE_USER_DICTIONARY",
			Status:      "normal",
			Description: "gravar no dicionário definido pelo usuário",
			Info:        "Permite a aplicação escrever novas palavras no dicionário do usuário.",
		},
		{
			Title:       "android.permission.READ_HISTORY_BOOKMARKS",
			Status:      "perigoso",
			Description: "ler histórico e os favoritos do navegador",
			Info:        "Permite a aplicação ler todos os URLs que o navegador visita e todos os favoritos do navegador.",
		},
		{
			Title:       "android.permission.WRITE_HISTORY_BOOKMARKS",
			Status:      "perigoso",
			Description: "escrever histórico e os favoritos do navegador",
			Info:        "Permite a aplicação modificar o histórico ou os favoritos do navegador capturar no seu telefone. Os aplicativos maliciosos podem usar isso para excluir ou modificar os dados do seu navegador.",
		},
		{
			Title:       "android.permission.SET_ALARM",
			Status:      "normal",
			Description: "definir alarme no despertador",
			Info:        "Permite a aplicação definir um alarme no aplicativo de alarme instalado. Alguns aplicativos de alarme podem não implementar esse recurso.",
		},
		{
			Title:       "android.permission.ACCESS_FINE_LOCATION",
			Status:      "perigoso",
			Description: "localização fina (GPS)",
			Info:        "Acesse fontes finas de localização, como o Sistema de Posicionamento Global no telefone, quando disponível. Aplicativos maliciosos podem usar isso para determinar onde você está e consumir energia adicional da bateria.",
		},
		{
			Title:       "android.permission.ACCESS_COARSE_LOCATION",
			Status:      "perigoso",
			Description: "localização aproximada (baseada na rede)",
			Info:        "Acesse fontes de localização aproximadas, como o banco de dados da rede móvel, para determinar uma localização aproximada do telefone, quando disponível. Aplicativos maliciosos podem usar isso para determinar aproximadamente onde você está.",
		},
		{
			Title:       "android.permission.ACCESS_MOCK_LOCATION",
			Status:      "perigoso",
			Description: "fontes falsas de localização para teste",
			Info:        "Crie fontes de localização falsas para teste. Aplicativos maliciosos podem usar isso para substituir uma localização e / ou status retornado por fontes de localização real, como GPS ou fornecedores de rede.",
		},
		{
			Title:       "android.permission.ACCESS_LOCATION_EXTRA_COMMANDS",
			Status:      "normal",
			Description: "acessar comandos adicionais de provedores de localização",
			Info:        "Acesse os comandos adicionais fornecidos pelo provedor de localização. Os aplicativos maliciosos podem usar isso para interferir na operação do GPS ou em outras fontes de localização.",
		},
		{
			Title:       "android.permission.INSTALL_LOCATION_PROVIDER",
			Status:      "cuidado",
			Description: "permissão para instalar um provedor de localização",
			Info:        "Crie fontes de localização falsas para teste. Aplicativos maliciosos podem usar isso para substituir uma localização e / ou status retornado por fontes de localização real, como fornecedores de GPS ou rede, ou monitorar e reportar sua localização em uma fonte externa",
		},
		{
			Title:       "android.permission.INTERNET",
			Status:      "perigoso",
			Description: "acesso total à Internet",
			Info:        "Permite a aplicação criar soquetes de rede.",
		},
		{
			Title:       "android.permission.ACCESS_NETWORK_STATE",
			Status:      "normal",
			Description: "visualizar status da rede",
			Info:        "Permite a aplicação visualizar o status de todas as redes.",
		},
		{
			Title:       "android.permission.ACCESS_WIFI_STATE",
			Status:      "normal",
			Description: "visualizar status do Wi-Fi",
			Info:        "Permite uma aplicação de visualização como informações sobre o status do Wi-Fi.",
		},
		{
			Title:       "android.permission.BLUETOOTH",
			Status:      "perigoso",
			Description: "Crie conexões Bluetooth",
			Info:        "Permite a aplicação visualizar a configuração do telefone Bluetooth local e fazer conexões com dispositivos emparelhados.",
		},
		{
			Title:       "android.permission.NFC",
			Status:      "perigoso",
			Description: "Controlam a comunicação em campo próximo",
			Info:        "Permite a aplicação comunicação com etiquetas, cartões e leitores de NFC (Near-Field Communication).",
		},
		{
			Title:       "android.permission.USE_SIP",
			Status:      "perigoso",
			Description: "Faça / receba chamadas pela Internet",
			Info:        "Permite a aplicação uso do serviço SIP para fazer / receber chamadas pela Internet.",
		},
		{
			Title:       "android.permission.ACCOUNT_MANAGER",
			Status:      "perigoso",
			Description: "Atua como o serviço de gerente de contas",
			Info:        "Permite a aplicação chamadas para Autenticadores de Conta",
		},
		{
			Title:       "android.permission.GET_ACCOUNTS",
			Status:      "normal",
			Description: "descobrir contas cadastradas",
			Info:        "Permite a aplicação acesso a uma lista de contas identificadas pelo telefone.",
		},
		{
			Title:       "android.permission.AUTHENTICATE_ACCOUNTS",
			Status:      "perigoso",
			Description: "atua como um autenticador de conta",
			Info:        "Permite a aplicação usar os recursos de autenticação de contas do Gerente de Contas, incluindo a criação de contas, bem como a identificação e configuração de suas senhas.",
		},
		{
			Title:       "android.permission.USE_CREDENTIALS",
			Status:      "perigoso",
			Description: "use como credenciais de autenticação de uma conta",
			Info:        "Permite a aplicação tokens de autenticação de solicitação.",
		},
		{
			Title:       "android.permission.MANAGE_ACCOUNTS",
			Status:      "perigoso",
			Description: "gerenciar uma lista de contas",
			Info:        "Permite a aplicação operações como adicionar e remover contas e excluir sua senha.",
		},
		{
			Title:       "android.permission.MODIFY_AUDIO_SETTINGS",
			Status:      "perigoso",
			Description: "altere suas configurações de áudio",
			Info:        "Permite que o aplicativo modifique como configurações globais de áudio, como volume e roteamento.",
		},
		{
			Title:       "android.permission.RECORD_AUDIO",
			Status:      "perigoso",
			Description: "gravar áudio",
			Info:        "Permite que o aplicativo acesse o caminho de gravação de áudio.",
		},
		{
			Title:       "android.permission.CAMERA",
			Status:      "perigoso",
			Description: "tire fotos e vídeos",
			Info:        "Permite que o aplicativo tire fotos e vídeos com a câmera. Isso permite que o aplicativo colete imagens que a câmera está vendo em qualquer momento.",
		},
		{
			Title:       "android.permission.VIBRATE",
			Status:      "normal",
			Description: "control vibrator",
			Info:        "Permite uma aplicação de controle do vibrador.",
		},
		{
			Title:       "android.permission.FLASHLIGHT",
			Status:      "normal",
			Description: "control flashlight",
			Info:        "Permite uma aplicação de controle da lanterna.",
		},
		{
			Title:       "android.permission.ACCESS_USB",
			Status:      "cuidado",
			Description: "Acessar dispositivos USB",
			Info:        "Permite a aplicação acesso a dispositivos USB.",
		},
		{
			Title:       "android.permission.HARDWARE_TEST",
			Status:      "perigoso",
			Description: "Hardware de teste",
			Info:        "Permite a aplicação controle de vários periféricos para fins de testes de hardware.",
		},
		{
			Title:       "android.permission.PROCESS_OUTGOING_CALLS",
			Status:      "perigoso",
			Description: "Interceptar chamadas efetuadas",
			Info:        "Permite que o aplicativo processe chamadas efetuadas e altere o número a ser discado. Os aplicativos maliciosos podem monitorar, redirecionar ou impedir chamadas efetuadas.",
		},
		{
			Title:       "android.permission.MODIFY_PHONE_STATE",
			Status:      "cuidado",
			Description: "Modificar status do telefone",
			Info:        "Permite a aplicação controle dos recursos de telefonia do dispositivo. Um aplicativo com permissão pode alternar entre redes, ligar e desligar o rádio do telefone e semelhante, sem nunca notificá-lo.",
		},
		{
			Title:       "android.permission.READ_PHONE_STATE",
			Status:      "perigoso",
			Description: "Ler estado e identidade do telefone",
			Info:        "Permite a aplicação acesso aos recursos de telefone do dispositivo. Um aplicativo com permissão pode determinar o número de telefone e o número de série deste telefone, se uma chamada estiver ativa, o número de chamada que está conectada etc . ",
		},
		{
			Title:       "android.permission.WRITE_EXTERNAL_STORAGE",
			Status:      "perigoso",
			Description: "Lê / modifica / apaga o conteúdo do cartão SD",
			Info:        "Permite uma aplicação de gravação no cartão SD.",
		},
		{
			Title:       "android.permission.READ_EXTERNAL_STORAGE",
			Status:      "perigoso",
			Description: "Ler o conteúdo do cartão SD",
			Info:        "Permite uma aplicação de leitura do cartão SD.",
		},
		{
			Title:       "android.permission.WRITE_SETTINGS",
			Status:      "perigoso",
			Description: "Modificar configurações globais do sistema",
			Info:        "Permite a aplicação modificação dos dados de configuração do sistema. Os aplicativos maliciosos podem corromper a configuração do sistema.",
		},
		{
			Title:       "android.permission.WRITE_SECURE_SETTINGS",
			Status:      "cuidado",
			Description: "Modificar configurações de segurança do sistema",
			Info:        "Permite a aplicação modificação de dados de configurações de segurança do sistema. Não é para ser usado com aplicativos comuns.",
		},
		{
			Title:       "android.permission.WRITE_GSERVICES",
			Status:      "cuidado",
			Description: "Modifique o mapa de serviços do Google",
			Info:        "Permite a aplicação modificação ou mapa de serviços do Google. Não é para ser usado com aplicativos comuns.",
		},
		{
			Title:       "android.permission.EXPAND_STATUS_BAR",
			Status:      "normal",
			Description: "expandir / coletar barra de status",
			Info:        "Permite que o aplicativo expanda ou oculte uma barra de status.",
		},
		{
			Title:       "android.permission.GET_TASKS",
			Status:      "perigoso",
			Description: "recuperar aplicativos em execução",
			Info:        "Permite que o aplicativo recupere informações sobre tarefas em execução recentes ou recentes. Pode permitir que aplicativos com intenções descubram informações privadas sobre outros aplicativos.",
		},
		{
			Title:       "android.permission.REORDER_TASKS",
			Status:      "perigoso",
			Description: "reordenar aplicativos em execução",
			Info:        "Permite a aplicação tarefas de movimentação para o primeiro plano e plano de fundo. Aplicativos maliciosos podem ser usados ​​para abrir para frente sem controle.",
		},
		{
			Title:       "android.permission.CHANGE_CONFIGURATION",
			Status:      "perigoso",
			Description: "altere as configurações da interface do usuário",
			Info:        "Permite a aplicação alteração da configuração atual, como localidade ou tamanho geral da fonte.",
		},
		{
			Title:       "android.permission.RESTART_PACKAGES",
			Status:      "normal",
			Description: "elimine processos em segundo plano",
			Info:        "Permite a aplicação processos de remoção de segundo plano de outros aplicativos, mesmo se a memória não estiver baixa.",
		},
		{
			Title:       "android.permission.KILL_BACKGROUND_PROCESSES",
			Status:      "normal",
			Description: "elimine processos em segundo plano",
			Info:        "Permite a aplicação processos de remoção de segundo plano de outros aplicativos, mesmo se a memória não estiver baixa.",
		},
		{
			Title:       "android.permission.FORCE_STOP_PACKAGES",
			Status:      "perigoso",
			Description: "forçar a parada de outras aplicações",
			Info:        "Permite a aplicação parar outros aplicativos à força.",
		},
		{
			Title:       "android.permission.DUMP",
			Status:      "cuidado",
			Description: "recuperar status interno do sistema",
			Info:        "Permite que o aplicativo recupere o status interno do sistema. Os aplicativos maliciosos podem recuperar uma grande variedade de informações privadas e de segurança das quais eles geralmente nunca usam.",
		},
		{
			Title:       "android.permission.SYSTEM_ALERT_WINDOW",
			Status:      "perigoso",
			Description: "exibir alertas no nível do sistema",
			Info:        "Permite a aplicação janelas de alerta do sistema. Aplicativos maliciosos podem invadir uma tela inteira do telefone.",
		},
		{
			Title:       "android.permission.SET_ANIMATION_SCALE",
			Status:      "perigoso",
			Description: "modifique a velocidade global da animação",
			Info:        "Permite a aplicação alterar a velocidade global da animação (animações mais rápidas ou mais lentas) a qualquer momento.",
		},
		{
			Title:       "android.permission.PERSISTENT_ACTIVITY",
			Status:      "perigoso",
			Description: "faça o aplicativo sempre rodar",
			Info:        "Permite a aplicação tornar partes persistentes, para que o sistema não possa usar para outros aplicativos.",
		},
		{
			Title:       "android.permission.GET_PACKAGE_SIZE",
			Status:      "normal",
			Description: "mede o espaço de armazenamento do aplicativo",
			Info:        "Permite a aplicação recuperar seu código, tamanho de dados e cache",
		},
		{
			Title:       "android.permission.SET_PREFERRED_APPLICATIONS",
			Status:      "perigoso",
			Description: "definir aplicativos preferidos",
			Info:        "Permite a aplicação modificar seus aplicativos preferidos. Isso pode permitir que aplicativos maliciosos alterem silenciosamente os aplicativos executados, falsificando seus aplicativos existentes para coletar dados particulares de você.",
		},
		{
			Title:       "android.permission.RECEIVE_BOOT_COMPLETED",
			Status:      "normal",
			Description: "iniciar automaticamente na inicialização",
			Info:        "Permite a aplicação iniciar automaticamente assim que o sistema terminar. Isso pode levar mais tempo para iniciar o telefone e permitir que o aplicativo desacelere o telefone geral, sempre utilizado.",
		},
		{
			Title:       "android.permission.BROADCAST_STICKY",
			Status:      "normal",
			Description: "enviar transmissão fixa",
			Info:        "Permite uma aplicação de envio persistente, que permanece após o término da transmissão. Os aplicativos maliciosos podem tornar o telefone lento ou instável, fazendo com que ele use muita memória.",
		},
		{
			Title:       "android.permission.WAKE_LOCK",
			Status:      "perigoso",
			Description: "impeça o telefone de dormir",
			Info:        "Permite a aplicação impedir que o telefone entre no modo de suspensão.",
		},
		{
			Title:       "android.permission.SET_WALLPAPER",
			Status:      "normal",
			Description: "definir papel de parede",
			Info:        "Permite a aplicação definir o papel de parede do sistema.",
		},
		{
			Title:       "android.permission.SET_WALLPAPER_HINTS",
			Status:      "normal",
			Description: "definir dicas de tamanho de papel de parede",
			Info:        "Permite a aplicação definir como dicas de tamanho de papel de parede do sistema.",
		},
		{
			Title:       "android.permission.SET_TIME",
			Status:      "cuidado",
			Description: "set time",
			Info:        "Permite uma aplicação de alteração de hora do telefone.",
		},
		{
			Title:       "android.permission.SET_TIME_ZONE",
			Status:      "perigoso",
			Description: "definir fuso horário",
			Info:        "Permite uma aplicação de alteração do horário do telefone.",
		},
		{
			Title:       "android.permission.MOUNT_UNMOUNT_FILESYSTEMS",
			Status:      "perigoso",
			Description: "montar e desmontar sistemas de arquivos",
			Info:        "Permite aplicar e desmontar sistemas de arquivos para armazenamento removível.",
		},
		{
			Title:       "android.permission.MOUNT_FORMAT_FILESYSTEMS",
			Status:      "perigoso",
			Description: "formatar armazenamento externo",
			Info:        "Permite uma aplicação de formato de armazenamento removível.",
		},
		{
			Title:       "android.permission.ASEC_ACCESS",
			Status:      "perigoso",
			Description: "Obter informações sobre armazenamento interno",
			Info:        "Permite a aplicação obter informações sobre armazenamento interno.",
		},
		{
			Title:       "android.permission.ASEC_CREATE",
			Status:      "perigoso",
			Description: "criar armazenamento interno",
			Info:        "Permite a aplicação criar armazenamento interno.",
		},
		{
			Title:       "android.permission.ASEC_DESTROY",
			Status:      "perigoso",
			Description: "destruição do armazenamento interno",
			Info:        "Permite uma aplicação de destruição do armazenamento interno.",
		},
		{
			Title:       "android.permission.ASEC_MOUNT_UNMOUNT",
			Status:      "perigoso",
			Description: "montar / desmontar armazenamento interno",
			Info:        "Permite a aplicação montar / desmontar armazenamento interno.",
		},
		{
			Title:       "android.permission.ASEC_RENAME",
			Status:      "perigoso",
			Description: "renomear armazenamento interno",
			Info:        "Permite uma aplicação de renomear armazenamento interno.",
		},
		{
			Title:       "android.permission.DISABLE_KEYGUARD",
			Status:      "perigoso",
			Description: "desativar bloqueio de teclas",
			Info:        "Permite a aplicação alteração de bloqueio de teclas e segurança de senha associada. Um exemplo legítimo disso é o telefone desativado ou o bloqueio de teclas para receber uma chamada telefônica e, em seguida, reativar ou bloquear as teclas quando a chamada está concluída. ",
		},
		{
			Title:       "android.permission.READ_SYNC_SETTINGS",
			Status:      "normal",
			Description: "leia configurações de sincronização",
			Info:        "Permite a aplicação leitura como configurações de sincronização, como se a sincronização estiver ativada para contatos.",
		},
		{
			Title:       "android.permission.WRITE_SYNC_SETTINGS",
			Status:      "perigoso",
			Description: "escrever configurações de sincronização",
			Info:        "Permite a aplicação modificação como configurações de sincronização, como se a sincronização estiver ativada para contatos.",
		},
		{
			Title:       "android.permission.READ_SYNC_STATS",
			Status:      "normal",
			Description: "leia estatísticas de sincronização",
			Info:        "Permite a aplicação leitura como estatísticas de sincronização; por exemplo, o histórico de sincronizações que ocorre.",
		},
		{
			Title:       "android.permission.WRITE_APN_SETTINGS",
			Status:      "perigoso",
			Description: "escrever configurações do nome do ponto de acesso",
			Info:        "Permite uma aplicação de modificação como configurações do APN, como Proxy e Porta de qualquer APN.",
		},
		{
			Title:       "android.permission.SUBSCRIBED_FEEDS_READ",
			Status:      "normal",
			Description: "leia feeds inscritos",
			Info:        "Permite a aplicação receber detalhes sobre os feeds sincronizados no momento.",
		},
		{
			Title:       "android.permission.SUBSCRIBED_FEEDS_WRITE",
			Status:      "perigoso",
			Description: "escreve feeds inscritos",
			Info:        "Permite a aplicação modificar seus feeds sincronizados no momento. Isso pode permitir que um aplicativo com intenção de alterar seus feeds sincronizados.",
		},
		{
			Title:       "android.permission.CHANGE_NETWORK_STATE",
			Status:      "perigoso",
			Description: "alterar a conectividade da rede",
			Info:        "Permite a aplicação alteração ou estado da conexão de rede.",
		},
		{
			Title:       "android.permission.CHANGE_WIFI_STATE",
			Status:      "perigoso",
			Description: "alterar o status do Wi-Fi",
			Info:        "Permite a aplicação conectar e desconectar pontos de acesso Wi-Fi e fazer alterações nas redes Wi-Fi configuradas.",
		},
		{
			Title:       "android.permission.CHANGE_WIFI_MULTICAST_STATE",
			Status:      "perigoso",
			Description: "permite a recepção Wi-Fi Multicast",
			Info:        "Permite a aplicação recebimento de pacotes não endereçados diretamente ao seu dispositivo. Isso pode ser útil na descoberta de serviços oferecidos nas ameaças. Ele consome mais energia do que o modo não multicast.",
		},
		{
			Title:       "android.permission.BLUETOOTH_ADMIN",
			Status:      "perigoso",
			Description: "administração bluetooth",
			Info:        "Permite a aplicação configurar o telefone Bluetooth local e descobrir e procurar com dispositivos remotos.",
		},
		{
			Title:       "android.permission.CLEAR_APP_CACHE",
			Status:      "perigoso",
			Description: "exclua todos os dados do cache do aplicativo",
			Info:        "Permite a aplicação armazenamento telefônico gratuito excluindo arquivos no diretório de cache do aplicativo. O acesso é muito restrito ao processo do sistema.",
		},
		{
			Title:       "android.permission.READ_LOGS",
			Status:      "perigoso",
			Description: "ler dados confidenciais do log",
			Info:        "Permite uma aplicação de leitura dos vários arquivos de log do sistema. Isso permite descobrir informações gerais sobre quem você está fazendo com o telefone, incluindo possíveis informações pessoais ou privadas.",
		},
		{
			Title:       "android.permission.SET_DEBUG_APP",
			Status:      "perigoso",
			Description: "ativar a depuração do aplicativo",
			Info:        "Permite a aplicação ativação da depuração para outro aplicativo. Aplicativos maliciosos podem usar isso para matar outros aplicativos.",
		},
		{
			Title:       "android.permission.SET_PROCESS_LIMIT",
			Status:      "perigoso",
			Description: "número limite de processos em execução",
			Info:        "Permite a aplicação controle do número máximo de processos que serão executados. Nunca é necessário para aplicativos comuns.",
		},
		{
			Title:       "android.permission.SET_ALWAYS_FINISH",
			Status:      "perigoso",
			Description: "fecha todos os aplicativos no segundo plano",
			Info:        "Permite a aplicação controle como atividades sempre concluídas da mesma forma que entram no segundo plano. Nunca são necessárias para aplicativos comuns.",
		},
		{
			Title:       "android.permission.SIGNAL_PERSISTENT_PROCESSES",
			Status:      "perigoso",
			Description: "envia sinais do Linux para aplicativos",
			Info:        "Permite que o aplicativo solicite que o sinal seja enviado a todos os processos persistentes.",
		},
		{
			Title:       "android.permission.DIAGNOSTIC",
			Status:      "perigoso",
			Description: "leitura / gravação em recursos pertencentes a diag",
			Info:        "Permite a aplicação leitura e gravação em qualquer recurso pertencente ao grupo diag; por exemplo, arquivos em / dev. Isso pode afetar a estabilidade e a segurança do sistema. Isso deve ser usado SOMENTE para diagnósticos de hardware usados ​​pelo fabricante ou operador",
		},
		{
			Title:       "android.permission.STATUS_BAR",
			Status:      "cuidado",
			Description: "alterar ou modificar a barra de status",
			Info:        "Permite que o aplicativo desative a barra de status ou adicione e remova ícones do sistema.",
		},
		{
			Title:       "android.permission.STATUS_BAR_SERVICE",
			Status:      "perigoso",
			Description: "barra de status",
			Info:        "Permite a aplicação ser uma barra de status.",
		},
		{
			Title:       "android.permission.FORCE_BACK",
			Status:      "perigoso",
			Description: "forçar o fechamento do aplicativo",
			Info:        "Permite a aplicação qualquer atividade que esteja no primeiro plano a fechar e voltar. Nunca deve ser necessário para aplicativos comuns.",
		},
		{
			Title:       "android.permission.UPDATE_DEVICE_STATS",
			Status:      "cuidado",
			Description: "modificar estatísticas da bateria",
			Info:        "Permite alterar estatísticas coletadas da bateria. Não é para ser usado com aplicativos comuns.",
		},
		{
			Title:       "android.permission.INTERNAL_SYSTEM_WINDOW",
			Status:      "perigoso",
			Description: "exibidas janelas não autorizadas",
			Info:        "Permite a criação de janelas que devem ser usadas pela interface do usuário do sistema interno. Não é para ser usado com aplicativos comuns.",
		},
		{
			Title:       "android.permission.MANAGE_APP_TOKENS",
			Status:      "perigoso",
			Description: "gerenciar tokens de aplicativos",
			Info:        "Permite que os aplicativos criem e gerem seus tokens únicos, ignorando sua ordem Z comum. Nunca deve ser necessário para aplicativos comuns.",
		},
		{
			Title:       "android.permission.INJECT_EVENTS",
			Status:      "perigoso",
			Description: "pressione as teclas e os botões de controle",
			Info:        "Permite a aplicação entregar seus próprios eventos de entrada (pressionamentos de tecla, etc.) para outros aplicativos. Aplicativos maliciosos podem usar isso para controlar o telefone.",
		},
		{
			Title:       "android.permission.SET_ACTIVITY_WATCHER",
			Status:      "perigoso",
			Description: "monitora e controla todo o lançamento de aplicativos",
			Info:        "Permite a aplicação monitoramento e controle de como o sistema inicia atividades. Como aplicativos maliciosos podem comprometer completamente o sistema. Essa permissão é necessária apenas para o desenvolvimento, nunca para o uso comum do telefone.",
		},
		{
			Title:       "android.permission.SHUTDOWN",
			Status:      "perigoso",
			Description: "desligamento parcial",
			Info:        "Colocar ou gerenciar atividades em um estado de desligamento. Não execute um desligamento completo.",
		},
		{
			Title:       "android.permission.STOP_APP_SWITCHES",
			Status:      "perigoso",
			Description: "impedir trocas de aplicativos",
			Info:        "Previna o usuário de alterar para outra aplicação.",
		},
		{
			Title:       "android.permission.READ_INPUT_STATE",
			Status:      "perigoso",
			Description: "registre o que você digita e as ações que executam",
			Info:        "Permite que os aplicativos observem como as teclas que você pressiona, mesmo ao interagir com outro aplicativo (como digitar uma senha). Nunca deve ser necessário para aplicativos comuns.",
		},
		{
			Title:       "android.permission.BIND_INPUT_METHOD",
			Status:      "perigoso",
			Description: "vincular a um método de entrada",
			Info:        "Permite que o proprietário vincule à interface de nível superior de um método de entrada. Nunca deve ser necessário para aplicativos comuns.",
		},
		{
			Title:       "android.permission.BIND_WALLPAPER",
			Status:      "cuidado",
			Description: "vincular ao papel de parede",
			Info:        "Permite ao proprietário vincular-se à interface de nível superior do papel de parede. Nunca deve ser necessário para aplicativos comuns.",
		},
		{
			Title:       "android.permission.BIND_DEVICE_ADMIN",
			Status:      "perigoso",
			Description: "interaja com o administrador do dispositivo",
			Info:        "Permite que o proprietário envie intenções ao administrador de dispositivos. Nunca deve ser necessário para aplicativos comuns.",
		},
		{
			Title:       "android.permission.SET_ORIENTATION",
			Status:      "perigoso",
			Description: "alterar orientação da tela",
			Info:        "Permite a aplicação alteração da tela a qualquer momento. Nunca deve ser necessário para aplicativos comuns.",
		},
		{
			Title:       "android.permission.INSTALL_PACKAGES",
			Status:      "cuidado",
			Description: "instale aplicativos diretamente",
			Info:        "Permite a aplicação instalação de pacotes novos ou de uso Android. Aplicativos maliciosos podem usar isso para adicionar novos aplicativos com aplicativos arbitrariamente poderosos.",
		},
		{
			Title:       "android.permission.REQUEST_INSTALL_PACKAGES",
			Status:      "perigoso",
			Description: "Permite uma aplicação de solicitação de instalação de pacotes.",
			Info:        "Aplicativos maliciosos podem usar isso para tentar induzir os usuários a instalar pacotes maliciosos adicionais.",
		},
		{
			Title:       "android.permission.CLEAR_APP_USER_DATA",
			Status:      "perigoso",
			Description: "apague os dados de outras aplicações",
			Info:        "Permite a aplicação dados claros do usuário.",
		},
		{
			Title:       "android.permission.DELETE_CACHE_FILES",
			Status:      "cuidado",
			Description: "excluindo os caches de outros aplicativos",
			Info:        "Permite a aplicação excluir arquivos de cache.",
		},
		{
			Title:       "android.permission.DELETE_PACKAGES",
			Status:      "cuidado",
			Description: "excluir aplicativos",
			Info:        "Permite a aplicação exclusão de pacotes do Android. Aplicativos maliciosos podem usar isso para excluir aplicativos importantes.",
		},
		{
			Title:       "android.permission.MOVE_PACKAGE",
			Status:      "cuidado",
			Description: "Mover recursos do aplicativo",
			Info:        "Permite a aplicação recursos de aplicativos de mídia interna para externa e vice-versa.",
		},
		{
			Title:       "android.permission.CHANGE_COMPONENT_ENABLED_STATE",
			Status:      "cuidado",
			Description: "ativar ou desativar componentes do aplicativo",
			Info:        "Permite a aplicação alteração se um componente de outro aplicativo for ativado ou desativado. Aplicativos maliciosos podem usar-lo para ativar recursos importantes do telefone. É importante ter cuidado com permissões, pois é possível incluir componentes do aplicativo estado inutilizável, inconsistente ou instável",
		},
		{
			Title:       "android.permission.ACCESS_SURFACE_FLINGER",
			Status:      "perigoso",
			Description: "acesse o SurfaceFlinger",
			Info:        "Permite que o aplicativo use os recursos de nível inferior do SurfaceFlinger.",
		},
		{
			Title:       "android.permission.READ_FRAME_BUFFER",
			Status:      "perigoso",
			Description: "leia o buffer do quadro",
			Info:        "Permite que o aplicativo leia o conteúdo do buffer de quadros.",
		},
		{
			Title:       "android.permission.BRICK",
			Status:      "perigoso",
			Description: "desativar permanentemente o telefone",
			Info:        "Permite a aplicação remover todo o telefone permanentemente. Isso é muito perigoso.",
		},
		{
			Title:       "android.permission.REBOOT",
			Status:      "cuidado",
			Description: "forçar reinicialização do telefone",
			Info:        "Permite uma aplicação de telefone ou reiniciar.",
		},
		{
			Title:       "android.permission.DEVICE_POWER",
			Status:      "perigoso",
			Description: "liga ou desliga o telefone",
			Info:        "Permite a aplicação ligar ou desligar o telefone.",
		},
		{
			Title:       "android.permission.FACTORY_TEST",
			Status:      "perigoso",
			Description: "executar no modo de teste de fábrica",
			Info:        "Executar como um teste de nível baixo do fabricante, permitir acesso completo ao hardware do telefone. Disponível apenas quando um telefone estiver sendo executado no modo de teste do fabricante.",
		},
		{
			Title:       "android.permission.BROADCAST_PACKAGE_REMOVED",
			Status:      "perigoso",
			Description: "enviar transmissão removida do pacote",
			Info:        "Permite a aplicação transmitir uma notificação de que um pacote de aplicativos foi removido. Os aplicativos maliciosas podem usar isso para eliminar qualquer outro aplicativo em execução.",
		},
		{
			Title:       "android.permission.BROADCAST_SMS",
			Status:      "perigoso",
			Description: "enviar transmissão recebida por SMS",
			Info:        "Permite a aplicação transmitir uma notificação de que uma mensagem SMS foi recebida. Os aplicativos maliciosos podem usar isso para forjar mensagens SMS recebidas.",
		},
		{
			Title:       "android.permission.BROADCAST_WAP_PUSH",
			Status:      "perigoso",
			Description: "envia transmissão recebida por WAP-PUSH",
			Info:        "Permite a aplicação transmitir uma notificação de que uma mensagem WAP-PUSH foi recebida. As aplicações maliciosas podem usar isso para forjar o recebimento de mensagens MMS ou substituir o conteúdo de qualquer página da Web silenciosamente por variantes maliciosas.",
		},
		{
			Title:       "android.permission.MASTER_CLEAR",
			Status:      "cuidado",
			Description: "redefinir o sistema para os padrões de fábrica",
			Info:        "Permite a aplicação redefinir completamente o sistema para as configurações de fábrica, apagando todos os dados, configurações e aplicativos instalados.",
		},
		{
			Title:       "android.permission.CALL_PRIVILEGED",
			Status:      "cuidado",
			Description: "ligue diretamente para qualquer número de telefone",
			Info:        "Permite a aplicação qualquer número de telefone, incluindo números de emergência, sem a sua intervenção. Aplicações maliciosas podem fazer chamadas desnecessárias e ilegais para serviços de emergência.",
		},
		{
			Title:       "android.permission.PERFORM_CDMA_PROVISIONING",
			Status:      "cuidado",
			Description: "inicia diretamente a configuração do telefone CDMA",
			Info:        "Permite a aplicação iniciar o provisionamento de CDMA. Os aplicativos maliciosos podem iniciar o provisionamento de CDMA desnecessariamente",
		},
		{
			Title:       "android.permission.CONTROL_LOCATION_UPDATES",
			Status:      "cuidado",
			Description: "controlar notificações de atualização de local",
			Info:        "Permite ativar / desativar notificações de atualização de localização do rádio. Não é para ser usado com aplicações comuns.",
		},
		{
			Title:       "android.permission.ACCESS_CHECKIN_PROPERTIES",
			Status:      "cuidado",
			Description: "acessar propriedades de check-in",
			Info:        "Permite acesso de leitura / gravação às propriedades carregadas pelo serviço de check-in. Não é para ser usado com aplicações comuns.",
		},
		{
			Title:       "android.permission.PACKAGE_USAGE_STATS",
			Status:      "perigoso",
			Description: "atualizar estatísticas de uso do componente",
			Info:        "Permite a modificação das estatísticas de uso de componentes coletados. Não é para ser usado com aplicativos comuns.",
		},
		{
			Title:       "android.permission.BATTERY_STATS",
			Status:      "normal",
			Description: "modificar estatísticas da bateria",
			Info:        "Permite a modificação das estatísticas coletadas da bateria. Não é para ser usado com aplicativos comuns.",
		},
		{
			Title:       "android.permission.BACKUP",
			Status:      "cuidado",
			Description: "backup e restauração do sistema de controle",
			Info:        "Permite a aplicação controle do mecanismo de backup e restauração do sistema. Não é para ser usado com aplicativos comuns.",
		},
		{
			Title:       "android.permission.BIND_APPWIDGET",
			Status:      "cuidado",
			Description: "escolha widgets",
			Info:        "Permite a aplicação informar ao sistema quais widgets podem ser usados ​​por qual aplicativo. Com essa permissão, os aplicativos podem acessar dados pessoais para outros aplicativos. Não é para ser usado com aplicativos comuns.",
		},
		{
			Title:       "android.permission.CHANGE_BACKGROUND_DATA_SETTING",
			Status:      "perigoso",
			Description: "altere a configuração de uso de dados em segundo plano",
			Info:        "Permite a aplicação alterar a configuração de uso de dados em segundo plano.",
		},
		{
			Title:       "android.permission.GLOBAL_SEARCH",
			Status:      "cuidado",
			Description: "",
			Info:        "",
		},
		{
			Title:       "android.permission.GLOBAL_SEARCH_CONTROL",
			Status:      "perigoso",
			Description: "",
			Info:        "",
		},
		{
			Title:       "android.permission.SET_WALLPAPER_COMPONENT",
			Status:      "cuidado",
			Description: "",
			Info:        "",
		},
		{
			Title:       "android.permission.ACCESS_CACHE_FILESYSTEM",
			Status:      "cuidado",
			Description: "acesse o sistema de arquivos em cache",
			Info:        "Permite a aplicação leitura e gravação no sistema de arquivos em cache.",
		},
		{
			Title:       "android.permission.COPY_PROTECTED_DATA",
			Status:      "perigoso",
			Description: "Permite chamar o serviço de contêiner padrão para copiar o conteúdo. Não é para ser usado com aplicativos comuns.",
			Info:        "Permite chamar o serviço de contêiner padrão para copiar o conteúdo. Não é para ser usado com aplicativos comuns.",
		},
		{
			Title:       "android.permission.C2D_MESSAGE",
			Status:      "perigoso",
			Description: "Permite que a nuvem envie mensagens para o dispositivo",
			Info:        "Permite a aplicação receber notificações push.",
		},
		{
			Title:       "android.permission.ADD_VOICEMAIL",
			Status:      "perigoso",
			Description: "adicione mensagens de voz ao sistema",
			Info:        "Permite a aplicação adicionar mensagens de voz ao sistema.",
		},
		{
			Title:       "android.permission.ACCEPT_HANDOVER",
			Status:      "perigoso",
			Description: "",
			Info:        "Permite que o aplicativo de chamada continue uma chamada iniciada em outro aplicativo. Um exemplo é um aplicativo de videochamada que deseja continuar uma chamada de voz na rede móvel do usuário.",
		},
		{
			Title:       "android.permission.ACCESS_NOTIFICATION_POLICY",
			Status:      "normal",
			Description: "",
			Info:        "Permissão do marcador para aplicativos que desejam acessar a política de notificação.",
		},
		{
			Title:       "android.permission.ANSWER_PHONE_CALLS",
			Status:      "perigoso",
			Description: "",
			Info:        "Permite uma aplicação de resposta a ligações.",
		},
		{
			Title:       "android.permission.BIND_ACCESSIBILITY_SERVICE",
			Status:      "perigoso",
			Description: "",
			Info:        "Deve ser exigido por um AccessibilityService, para garantir que apenas o sistema possa se vincular a ele.",
		},
		{
			Title:       "android.permission.BIND_AUTOFILL_SERVICE",
			Status:      "perigoso",
			Description: "",
			Info:        "Deve ser exigido por um AutofillService, para garantir que apenas o sistema possa se vincular a ele.",
		},
		{
			Title:       "android.permission.BIND_CARRIER_MESSAGING_SERVICE",
			Status:      "normal",
			Description: "",
			Info:        "O processo do sistema que é permitido vincular aos serviços nos aplicativos da operadora terá essa permissão.",
		},
		{
			Title:       "android.permission.BIND_CARRIER_SERVICES",
			Status:      "perigoso",
			Description: "",
			Info:        "O processo do sistema que pode se vincular aos serviços nos aplicativos da operadora terá essa permissão. Os aplicativos da operadora devem usar essa permissão para proteger seus serviços aos quais somente o sistema está autorizado.",
		},
		{
			Title:       "android.permission.BIND_CHOOSER_TARGET_SERVICE",
			Status:      "perigoso",
			Description: "",
			Info:        "Deve ser exigido por um ChooserTargetService, para garantir que apenas o sistema possa se vincular a ele",
		},
		{
			Title:       "android.permission.BIND_CONDITION_PROVIDER_SERVICE",
			Status:      "perigoso",
			Description: "",
			Info:        "Deve ser exigido por um ConditionProviderService, para garantir que apenas o sistema possa se vincular a ele",
		},
		{
			Title:       "android.permission.BIND_DREAM_SERVICE",
			Status:      "perigoso",
			Description: "",
			Info:        "Deve ser exigido por um DreamService, para garantir que apenas o sistema possa se vincular a ele.",
		},
		{
			Title:       "android.permission.BIND_INCALL_SERVICE",
			Status:      "perigoso",
			Description: "",
			Info:        "Deve ser exigido por um InCallService, para garantir que apenas o sistema possa se vincular a ele.",
		},
		{
			Title:       "android.permission.BIND_MIDI_DEVICE_SERVICE",
			Status:      "perigoso",
			Description: "",
			Info:        "Deve ser exigido por um MidiDeviceService, para garantir que apenas o sistema possa se vincular a ele.",
		},
		{
			Title:       "android.permission.BIND_NFC_SERVICE",
			Status:      "perigoso",
			Description: "",
			Info:        "Deve ser exigido por um HostApduService ou OffHostApduService para garantir que apenas o sistema possa se vincular a ele.",
		},
		{
			Title:       "android.permission.BIND_NOTIFICATION_LISTENER_SERVICE",
			Status:      "perigoso",
			Description: "",
			Info:        "Deve ser exigido por um NotificationListenerService, para garantir que apenas o sistema possa se vincular a ele.",
		},
		{
			Title:       "android.permission.BIND_PRINT_SERVICE",
			Status:      "perigoso",
			Description: "",
			Info:        "Deve ser exigido por um PrintService, para garantir que apenas o sistema possa se vincular a ele.",
		},
		{
			Title:       "android.permission.BIND_QUICK_SETTINGS_TILE",
			Status:      "normal",
			Description: "",
			Info:        "Permite uma aplicação de ligação a blocos de configurações rápidas de terceiros.",
		},
		{
			Title:       "android.permission.BIND_REMOTEVIEWS",
			Status:      "normal",
			Description: "",
			Info:        "Deve ser exigido por um RemoteViewsService, para garantir que apenas o sistema possa se vincular a ele.",
		},
		{
			Title:       "android.permission.BIND_SCREENING_SERVICE",
			Status:      "perigoso",
			Description: "",
			Info:        "Deve ser exigido por um CallScreeningService, para garantir que apenas o sistema possa se vincular a ele.",
		},
		{
			Title:       "android.permission.BIND_TELECOM_CONNECTION_SERVICE",
			Status:      "perigoso",
			Description: "",
			Info:        "Deve ser exigido por um ConnectionService, para garantir que apenas o sistema possa se vincular a ele.",
		},
		{
			Title:       "android.permission.BIND_TEXT_SERVICE",
			Status:      "perigoso",
			Description: "",
			Info:        "Deve ser exigido por um TextService (por exemplo, SpellCheckerService) para garantir que apenas o sistema possa se vincular a ele.",
		},
		{
			Title:       "android.permission.BIND_TV_INPUT",
			Status:      "perigoso",
			Description: "",
			Info:        "Deve ser exigido por um TvInputService para garantir que apenas o sistema possa se vincular a ele.",
		},
		{
			Title:       "android.permission.BIND_VISUAL_VOICEMAIL_SERVICE",
			Status:      "perigoso",
			Description: "",
			Info:        "Deve ser exigido por um link",
		},
		{
			Title:       "android.permission.BIND_VOICE_INTERACTION",
			Status:      "perigoso",
			Description: "",
			Info:        "Deve ser exigido por um VoiceInteractionService, para garantir que apenas o sistema possa se vincular a ele.",
		},
		{
			Title:       "android.permission.BIND_VPN_SERVICE",
			Status:      "perigoso",
			Description: "",
			Info:        "Deve ser exigido por um VpnService, para garantir que apenas o sistema possa se vincular a ele.",
		},
		{
			Title:       "android.permission.BIND_VR_LISTENER_SERVICE",
			Status:      "perigoso",
			Description: "",
			Info:        "Deve ser exigido por um VrListenerService, para garantir que apenas o sistema possa se vincular a ele.",
		},
		{
			Title:       "android.permission.BLUETOOTH_PRIVILEGED",
			Status:      "normal",
			Description: "",
			Info:        "Permite que os aplicativos emparelhem dispositivos bluetooth sem a interação do usuário e permita ou não o acesso à agenda telefônica ou ao acesso a mensagens. Isso não está disponível para aplicativos de terceiros.",
		},
		{
			Title:       "android.permission.BODY_SENSORS",
			Status:      "perigoso",
			Description: "",
			Info:        "Permite a aplicação acesso a dados de sensores que o usuário utiliza para medir o que está acontecendo dentro de seu corpo, como freqüência cardíaca.",
		},
		{
			Title:       "android.permission.CAPTURE_AUDIO_OUTPUT",
			Status:      "normal",
			Description: "",
			Info:        "Permite uma aplicação de captura de saída de áudio.",
		},
		{
			Title:       "android.permission.CAPTURE_SECURE_VIDEO_OUTPUT",
			Status:      "normal",
			Description: "",
			Info:        "Permite uma aplicação de captura de saída de vídeo segura.",
		},
		{
			Title:       "android.permission.CAPTURE_VIDEO_OUTPUT",
			Status:      "normal",
			Description: "",
			Info:        "Permite uma aplicação de captura de saída de vídeo.",
		},
		{
			Title:       "android.permission.FOREGROUND_SERVICE",
			Status:      "normal",
			Description: "",
			Info:        "Permite que o aplicativo comum use",
		},
		{
			Title:       "android.permission.GET_ACCOUNTS_PRIVILEGED",
			Status:      "normal",
			Description: "",
			Info:        "Permite acesso à lista de contas no Serviço de Contas.",
		},
		{
			Title:       "android.permission.INSTALL_SHORTCUT",
			Status:      "normal",
			Description: "",
			Info:        "Permite a aplicação instalar um atalho no Launcher.",
		},
		{
			Title:       "android.permission.INSTANT_APP_FOREGROUND_SERVICE",
			Status:      "normal",
			Description: "",
			Info:        "Permite que o aplicativo instantâneo crie serviços em primeiro plano.",
		},
		{
			Title:       "android.permission.LOCATION_HARDWARE",
			Status:      "normal",
			Description: "",
			Info:        "Permite a aplicação usar recursos de localização em hardware, como a API de geofencing.",
		},
		{
			Title:       "android.permission.MANAGE_DOCUMENTS",
			Status:      "perigoso",
			Description: "",
			Info:        "Permite a aplicação gerenciar o acesso a documentos, geralmente como parte de um seletor de documentos.",
		},
		{
			Title:       "android.permission.MANAGE_OWN_CALLS",
			Status:      "normal",
			Description: "",
			Info:        "Permite a um aplicativo de chamada que gerencia suas próprias chamadas através do autogerenciamento",
		},
		{
			Title:       "android.permission.MEDIA_CONTENT_CONTROL",
			Status:      "normal",
			Description: "",
			Info:        "Permite a aplicação saber qual conteúdo está sendo reproduzido e controlar sua reprodução.",
		},
		{
			Title:       "android.permission.NFC_TRANSACTION_EVENT",
			Status:      "normal",
			Description: "",
			Info:        "Permite que os aplicativos recebam eventos de transação NFC.",
		},
		{
			Title:       "android.permission.READ_CALL_LOG",
			Status:      "perigoso",
			Description: "",
			Info:        "Permite a aplicação ler o registro de chamadas do usuário.",
		},
		{
			Title:       "android.permission.READ_PHONE_NUMBERS",
			Status:      "perigoso",
			Description: "",
			Info:        "Permite acesso de leitura aos números de telefone do dispositivo. Esse é um subconjunto dos recursos concedidos por",
		},
		{
			Title:       "android.permission.READ_VOICEMAIL",
			Status:      "perigoso",
			Description: "",
			Info:        "Permite a aplicação leitura de mensagens de voz no sistema.",
		},
		{
			Title:       "android.permission.REQUEST_COMPANION_RUN_IN_BACKGROUND",
			Status:      "normal",
			Description: "",
			Info:        "Permite uma aplicação 'Companheira' de rodar no segundo plano.",
		},
		{
			Title:       "android.permission.REQUEST_COMPANION_USE_DATA_IN_BACKGROUND",
			Status:      "normal",
			Description: "",
			Info:        "Permite uma aplicação 'Companheira' de usar dados no segundo plano.",
		},
		{
			Title:       "android.permission.REQUEST_DELETE_PACKAGES",
			Status:      "normal",
			Description: "",
			Info:        "Permite uma aplicação de solicitação de exclusão de pacotes. Aplicativos direcionados a APIs",
		},
		{
			Title:       "android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS",
			Status:      "normal",
			Description: "",
			Info:        "Permissão que um aplicativo deve manter para poder usar",
		},
		{
			Title:       "android.permission.SEND_RESPOND_VIA_MESSAGE",
			Status:      "normal",
			Description: "",
			Info:        "Permite que o aplicativo (Telefone) envie uma solicitação a outros aplicativos para lidar com a ação de resposta por mensagem durante as chamadas recebidas.",
		},
		{
			Title:       "android.permission.TRANSMIT_IR",
			Status:      "normal",
			Description: "",
			Info:        "Permite usar o transmissor IR do dispositivo, se disponível.",
		},
		{
			Title:       "android.permission.UNINSTALL_SHORTCUT",
			Status:      "normal",
			Description: "",
			Info:        "Não use essa permissão no seu aplicativo. Esta permissão não é mais suportada.",
		},
		{
			Title:       "android.permission.USE_BIOMETRIC",
			Status:      "normal",
			Description: "",
			Info:        "Permite que o aplicativo use modalidades biométricas compatíveis com o dispositivo.",
		},
		{
			Title:       "android.permission.USE_FINGERPRINT",
			Status:      "normal",
			Description: "",
			Info:        "Essa constante foi descontinuada na API nível 28. Os aplicativos devem requerer USE_BIOMETRIC no lugar.",
		},
		{
			Title:       "android.permission.WRITE_CALL_LOG",
			Status:      "perigoso",
			Description: "",
			Info:        "Permite uma aplicação de gravação (mas não leitura) dos dados do log de chamadas do usuário.",
		},
		{
			Title:       "android.permission.WRITE_VOICEMAIL",
			Status:      "perigoso",
			Description: "",
			Info:        "Permite a aplicação modificação e remoção de erros de voz existentes no sistema.",
		},
	}
}
